name: CI

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Convert Markdown into PDF
        uses: KoharaKazuya/marp-cli-action@v2
        with:
          generate-html: false
          generate-pdf: true

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compilers_101.pdf
          path: ./compilers_101.pdf

